### ISSUE TITLE
poster_  missing

### ISSUE THREAD

**Issue by maxigit** [chrisdone/lucid#43]
The [poster](http://www.w3schools.com/tags/att_video_poster.asp)  attribute is missing
poster_ = mkAttribute "poster"

**Comment by chris-martin** [comment]
Why is this closed? It seems like there's a handful of other [video](https://www.w3.org/TR/html5/semantics-embedded-content.html#the-video-element) attributes that are missing as well.

**Comment by phadej** [comment]
Probably because `poster_` is only in HTML5.2 which is fairly recent: *W3C Recommendation, 14 December 2017*. I think supporting non-recommendations is not good use of resources for `lucid` anyway.

`poster_` is not only thing missing. See https://github.com/chrisdone/lucid/issues/85. I'll happily review more complete pull requests, than just adding a single attribute.
