### ISSUE TITLE
Integrate lucid-from-html

### ISSUE THREAD

**Issue by dbaynard** [chrisdone/lucid#70]
[lucid-from-html](https://github.com/dbaynard/lucid-from-html) converts html into the lucid DSL, but is an experimental program. Once it is stable, it may be worth integrating into lucid itself, as discussed in #16 .

If this is desirable, this issue should track requirements for that program to be merged into lucid.

**Comment by dbaynard** [comment]
@phadej Think we should do this? The executable has had some use and hasn't thrown up any issues, so far.

**Comment by phadej** [comment]
I'll be busy over holidays, but let's put the executable into `lucid` early next year

**Comment by alexanderkjeldaas** [comment]
I just wrote some blaze-html code because of that tool.  It's 100% essential when working with designers in any meaningful way.  To put it another way, I can't *not* use blaze-html.  Maybe I can use lucid in addition, but I absolutely must have a tool that can take what's being output by some designer's tool and convert it into my haskell DSL.

**Comment by dbaynard** [comment]
This wouldn't in any way replace blaze.

On another note. @alogic0 pointed out some difficulties with this plan, and has taken over lucid-from-html, which is probably better as a separate tool.
