### ISSUE TITLE
How does renderBS deal with Text inside the HtmlT monad?

### ISSUE THREAD

**Issue by saurabhnanda** [chrisdone/lucid#77]
If I have two versions of the following snippet:

```
storefrontAngularApp :: Html ()
storefrontAngularApp = div_ $ do
  script_ [type_ "text/javascript", src_ "inline.bundle.js"] ("" :: Text)
```

vs

```
storefrontAngularApp :: Html ()
storefrontAngularApp = div_ $ do
  script_ [type_ "text/javascript", src_ "inline.bundle.js"] ("" :: BSL.ByteString)
```

...and I call `renderBS storefrontAngularApp` on both of them -- it works. How is Lucid handling Text/ByteString internally? Is this going to have any perf impact? Is one preferred over the other? Is it possible at all to use hard-coded strings without having to annotate their types and letting the `render*` function figure out which type to use?

Possibly related to #44

**Comment by saurabhnanda** [comment]
Possible a related issue:

```
storefrontAngularApp :: Html ()
storefrontAngularApp = div_ $ do
  -- NOTE: If I add a type annotation to the following line it doesn't compile...
  term "app-flexi-payment" ""

  -- ... but, UNLESS I add a type annotation to the following, it doesn't compile!
  script_ [type_ "text/javascript", src_ "inline.bundle.js"] ("" :: BSL.ByteString)
```

How come, type-annotation is required in one call-site and not the other?

**Comment by chrisdone** [comment]
Text will be encoded to UTF8. The ByteString is assumed to be already UTF8-encoded. Both will be entity-escaped when rendered. I wouldn't expect a big performance difference between them, but ByteString usually has better performance characteristics because it contains less information.

Regarding not putting type annotations on strings, you can enable `ExtendedDefaultRules` which helps GHC to pick an instance of `IsString`:

```haskell
{-# LANGUAGE OverloadedStrings, ExtendedDefaultRules #-}
import Lucid
storefrontAngularApp :: Html ()
storefrontAngularApp = div_ $ do
  script_ [type_ "text/javascript", src_ "inline.bundle.js"] "hello!"
```

**Comment by chrisdone** [comment]
> Possible a related issue:
> 
> ```haskell
> storefrontAngularApp :: Html ()
> storefrontAngularApp = div_ $ do
>   -- NOTE: If I add a type annotation to the following line it doesn't compile...
>   term "app-flexi-payment" ""
> 
>   -- ... but, UNLESS I add a type annotation to the following, it doesn't compile!
>   script_ [type_ "text/javascript", src_ "inline.bundle.js"] ("" :: BSL.ByteString)
> ```
> 
> How come, type-annotation is required in one call-site and not the other?

Look at the type of `term`:

```haskell 
class Term arg result | result -> arg where
  term :: Data.Text.Internal.Text -> arg -> result
``` 

There are only two instances of this class:

```haskell
instance Monad m => Term (HtmlT m a) (HtmlT m a)
instance (Monad m, f ~ HtmlT m a) =>  Term [Attribute] (f -> HtmlT m a)
```

The first is the instance which is picked, because we know that the second argument, i.e. the result, is `HtmlT m a`. Normally, this wouldn't be enough because type class head unification goes in one direction. But the functional dependency shown in the class above `result -> arg` says "result uniquely determines arg", i.e. `HtmlT m a` can be used to infer `HtmlT m a`. Therefore via the instance, we know what the type is expected, and the `IsString` instance can be determined as `HtmlT m a`.

**Comment by saurabhnanda** [comment]
> Regarding not putting type annotations on strings, you can enable ExtendedDefaultRules which helps GHC to pick an instance of IsString:

Which type will GHC pick if `ExtendedDefaultRules` is used?

**Comment by saurabhnanda** [comment]
> The first is the instance which is picked, because we know that the second argument, i.e. the result, is HtmlT m a. Normally, this wouldn't be enough because type class head unification goes in one direction. But the functional dependency shown in the class above result -> arg says "result uniquely determines arg", i.e. HtmlT m a can be used to infer HtmlT m a. Therefore via the instance, we know what the type is expected, and the IsString instance can be determined as HtmlT m a.

Is there any way to add helpful hints to compiler errors for most of these gotchas when using Lucid?

**Comment by chrisdone** [comment]
I did write that you should use `ExtendedDefaultRules` in the docs near the top: http://hackage.haskell.org/package/lucid-2.9.9/docs/Lucid.html

That's about as much as I can do.

**Comment by saurabhnanda** [comment]
> I did write that you should use ExtendedDefaultRules in the docs near the top: http://hackage.haskell.org/package/lucid-2.9.9/docs/Lucid.html

Sorry, my bad that I skimmed through that part.
